### ISSUE TITLE
[Bug] Creating tasks does not work with 4.0.19 maproulette backend version.

### ISSUE THREAD

**Issue by arkmac** [maproulette/maproulette-java-client#67]
I've got following code in my project:
```java
var configuration =  new MapRouletteConfiguration(mapRouletteUri.getScheme(), mapRouletteUri.getHost(), mapRouletteUri.getPort(), projectName, instance.getApiKey());
var taskAPI = new TaskAPI(configuration);
var geojson = "{\"type\":\"Feature\",\"geometry\":{\"type\":\"Point\",\"coordinates\":[19.3584712,51.5606253]}, \"properties\":{\"osm_id\": "1751463324\", \"type\": \"node\"}}"

final var task = Task.builder(challengeId, Long.toString(feature.getOsmId()))
            .addGeojson(geojson)
            .priority(ChallengePriority.LOW)
            .build();
var created = taskAPI.create(task);
```
This worked up to version 4.0.18 of backend. 
With the latest backend version I get the following error:
```
org.maproulette.client.exception.MapRouletteException: Invalid response status code 400 - {"status":"KO","message":{"obj.modified":[{"msg":["error.path.missing"],"args":[]}]}}
org.maproulette.client.exception.MapRouletteRuntimeException: org.maproulette.client.exception.MapRouletteException: Invalid response status code 400 - {"status":"KO","message":{"obj.modified":[{"msg":["error.path.missing"],"args":[]}]}}
	at org.maproulette.client.utilities.ThrowingFunction.apply(ThrowingFunction.java:32)
	at org.maproulette.client.connection.Query.execute(Query.java:107)
	at org.maproulette.client.connection.MapRouletteConnection.execute(MapRouletteConnection.java:63)
	at org.maproulette.client.api.TaskAPI.create(TaskAPI.java:83)
        ...
```

For now I'm using a locally altered version of client lib where I added `modified` field of type `String` to `Task` to work around this issue.

**Comment by mgcuthbert** [comment]
There was an issue introduced that broke the API in the 4.0.19 release of MapRoulette. There is a new revision for MapRoulette forth coming, which should resolve this issue.

**Comment by ljdelight** [comment]
The maproulette-backend project runs a github action that run executes the maproulette-java-client integration tests, so this shouldn't happen in the future. Closing. Thanks for the patch!
